apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  strategy:
    type: {{ .Values.deployment.strategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deployment.strategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deployment.strategy.rollingUpdate.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
        - name: nginx-config
          configMap:
            name: {{ .Values.configMap.nginx }}
        - name: homework-config
          configMap:
            name: {{ .Values.configMap.homework }}
      initContainers:
        - name: {{ .Values.initContainers.name }}
          image: {{ .Values.initContainers.image }}
          command: {{ .Values.initContainers.command }}
          volumeMounts:
            - name: shared-volume
              mountPath: {{ .Values.volumeMounts.sharedVolume }}
      containers:
        - name: {{ .Values.containers.webServer.name }}
          image: {{ .Values.containers.webServer.image }}
          ports:
            - containerPort: {{ .Values.containers.webServer.port }}
          volumeMounts:
            - name: shared-volume
              mountPath: {{ .Values.volumeMounts.sharedVolume }}
            - name: nginx-config
              mountPath: {{ .Values.volumeMounts.nginxConfig }}
            - name: homework-config
              mountPath: {{ .Values.volumeMounts.homeworkConfig }}
          readinessProbe:
            exec:
              command: {{ .Values.containers.webServer.readinessProbe.command }}
            initialDelaySeconds: {{ .Values.containers.webServer.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.containers.webServer.readinessProbe.periodSeconds }}
        - name: {{ .Values.containers.metricsContainer.name }}
          image: {{ .Values.containers.metricsContainer.image }}
          command: {{ .Values.containers.metricsContainer.command }}
          volumeMounts:
            - name: shared-volume
              mountPath: {{ .Values.volumeMounts.sharedVolume }}

