# Default values for my-app.

namespace: homework

deployment:
  name: homework-deployment
  replicas: 3
  app: homework-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

serviceAccount:
  name: monitoring

clusterRole:
  name: metrics-reader
  rules:
    - nonResourceURLs:
      - "/metrics"
      - "/healthz"
      - "/livez"
      - "/readyz"
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["nodes", "pods", "services"]
      verbs: ["get", "list", "watch"]

clusterRoleBinding:
  name: monitoring-metrics-reader

pvc:
  name: homework-pvc

configMap:
  name: homework-configmap
  data:
    NGINX_CONFIG: nginx-config
    HOMEWORK_CONFIG: homework-configmap
    # Add any additional key-value pairs here

volumeMounts:
  sharedVolume: /homework
  nginxConfig: /etc/nginx/conf.d
  homeworkConfig: /homework/conf

initContainers:
  name: init-container
  image: busybox
  command: ['sh', '-c', 'echo "<html><body><h1>Hello, World!</h1></body></html>" > /homework/index.html']

containers:
  webServer:
    name: web-server
    image: nginx
    port: 80
    readinessProbe:
      command: ["test", "-f", "/homework/index.html"]
      initialDelaySeconds: 5
      periodSeconds: 5
  metricsContainer:
    name: metrics-container
    image: curlimages/curl
    command: ['sh', '-c', 'while true; do curl -s http://localhost/metrics > /homework/metrics; sleep 60; done']

# Keep the rest of the existing values as they are

serviceMonitor:
  name: homework-servicemonitor
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
