replicaCount: 3

image:
  repository: nginx
  tag: latest

service:
  port: 80

configMap:
  data:
    key1: value1
    key2: value2
    # Add more key-value pairs as needed

serviceAccount:
  name: monitoring-sa
  namespace: default
  annotations: {}
    # kubernetes.io/enforce-mountable-secrets: "true"

namespace:
  name: my-namespace
  labels:
    environment: development
    # Add more labels as needed
