replicaCount: 3

image:
  repository: nginx
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 80

configMap:
  data:
    key1: value1
    key2: value2
    # Add more key-value pairs as needed

serviceAccount:
  name: monitoring-sa
  namespace: default
  annotations: {}
    # kubernetes.io/enforce-mountable-secrets: "true"

namespace:
  name: my-namespace
  labels:
    environment: development
    # Add more labels as needed

serviceMonitor:
  name: my-service-monitor
  labels:
    release: prometheus
  selector:
    app: my-app
  namespace: my-namespace
  endpoints:
    - port: http-metrics
      interval: 15s
    - port: additional-metrics
      interval: 30s
      path: /metrics

storageClass:
  name: standard
  provisioner: kubernetes.io/gce-pd
  parameters:
    type: pd-standard
    fstype: ext4
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
