apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
            root /homework;
            index index.html;
        }
    }

