apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.serviceMonitor.name }}
  {{- with .Values.serviceMonitor.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.serviceMonitor.selector | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitor.namespace }}
  endpoints:
  {{- range .Values.serviceMonitor.endpoints }}
  - port: {{ .port }}
    interval: {{ .interval }}
    {{- if .path }}
    path: {{ .path }}
    {{- end }}
  {{- end }}
